export const ingredientes = [
  { id: 1, name: 'Salsa de tomate', extraCost: 0.5 },
  { id: 2, name: 'Mozzarella', extraCost: 1.5 },
  { id: 3, name: 'Albahaca', extraCost: 0.3 },
  { id: 4, name: 'Salame', extraCost: 2.0 },
  { id: 5, name: 'Champiñones', extraCost: 1.0 },
  { id: 6, name: 'Cebolla', extraCost: 0.6 },
  { id: 7, name: 'Pimientos verdes', extraCost: 0.7 },
  { id: 8, name: 'Aceitunas verdes', extraCost: 0.8 },
  { id: 9, name: 'Aceitunas negras', extraCost: 0.8 },
  { id: 10, name: 'Salchicha', extraCost: 1.8 },
  { id: 11, name: 'Panceta', extraCost: 2.2 },
  { id: 12, name: 'Jamón', extraCost: 1.7 },
  { id: 13, name: 'Ananá', extraCost: 1.2 },
  { id: 14, name: 'Espinaca', extraCost: 0.9 },
  { id: 15, name: 'Rúcula', extraCost: 1.0 },
  { id: 16, name: 'Anchoas', extraCost: 2.5 },
  { id: 17, name: 'Tomates frescos', extraCost: 1.1 },
  { id: 18, name: 'Queso parmesano', extraCost: 1.4 },
  { id: 19, name: 'Queso Roquefort', extraCost: 2.3 },
  { id: 20, name: 'Queso chedar', extraCost: 1.4 },
  { id: 21, name: 'Orégano', extraCost: 0.2 },
  { id: 22, name: 'Huevo', extraCost: 0.9 },
  { id: 23, name: 'Atún', extraCost: 1.9 },
  { id: 24, name: 'Morrones', extraCost: 1.7 },
  { id: 25, name: 'Jamón crudo', extraCost: 2.5 },
  { id: 26, name: 'Salsa Golf', extraCost: 1.2 },
  { id: 27, name: 'Ajo', extraCost: 0.4 },
  { id: 28, name: 'Perejil', extraCost: 0.3 },
  { id: 29, name: 'Palmitos', extraCost: 1.8 },
  { id: 30, name: 'Queso provolone', extraCost: 1.8 },
  { id: 31, name: 'Barbacoa', extraCost: 1.2 },
  { id: 32, name: 'Cerezas', extraCost: 1.9 },
];
