-- AlterTable
ALTER TABLE `order` ADD COLUMN `status` ENUM('PROCESSING', 'PREPARING', 'READY', 'DELIVERING', 'DELIVERED') NOT NULL DEFAULT 'PROCESSING';

-- AlterTable
ALTER TABLE `pizza` ADD COLUMN `image` VARCHAR(191) NULL;
