use custompizza;
-- AlterTable
ALTER TABLE `Order` ADD COLUMN `status` ENUM('PROCESSING', 'PREPARING', 'READY', 'DELIVERING', 'DELIVERED') NOT NULL DEFAULT 'PROCESSING';

-- AlterTable
ALTER TABLE `Pizza` ADD COLUMN `image` VARCHAR(191) NULL;
